# Exercise 2

In [1]:
import numpy as np
import pandas as pd

/var/folders/xy/0br9tjv92ygfx1xdz070c1l40000gn/T/ipykernel_1061/1662815981.py:2: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas as pd


## Task 1: Numpy


Create a 3×3 numpy array of all True’s

In [2]:
true_array = np.empty((3, 3), dtype=bool)

# Setze alle Werte auf True
true_array[:] = True

print(true_array)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


Create a 1D array of numbers from 0 to 9 and store it as arr

In [3]:
arr = np.arange(0,10,1)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


Extract all odd numbers from arr

In [4]:
arrOdd = list(filter(lambda x: x %2 == 1, arr))
print(arrOdd)

[1, 3, 5, 7, 9]


create a new array arr2 with all odd numbers in arr replaced with -1 using np.where()

In [5]:
arr2 = np.where(arr % 2 == 0, arr, -1)
print(arr2)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10 and store it as arr_2d

In [6]:
arr_2d = np.random.uniform(5, 10, size=(5, 3))
print(arr_2d)

[[5.24264863 5.43524832 5.79723513]
 [6.61474114 6.39999847 8.41069979]
 [7.57105258 8.82727778 6.24080962]
 [7.86897308 7.30623778 7.66077474]
 [7.48313339 8.00491608 8.23493398]]


Look up the meaning of colons in the context of sequences, eg. arr[0::3]. When and how can it be used?

In [7]:
# The general syntax for slicing is start:stop:step.
# 0 is the starting index.
# :: indicates that the slice includes all elements.
# 3 is the step, which means every third element is selected.

Reverse the rows of the 2D array arr_2d

In [8]:
# Reverse the rows
arr_2d_reversed_rows = arr_2d[::-1, :]

print(arr_2d_reversed_rows)

[[7.48313339 8.00491608 8.23493398]
 [7.86897308 7.30623778 7.66077474]
 [7.57105258 8.82727778 6.24080962]
 [6.61474114 6.39999847 8.41069979]
 [5.24264863 5.43524832 5.79723513]]


Reverse the columns of the 2D array arr_2d

In [9]:
# Reverse the rows
arr_2d_reversed_cols = arr_2d[:, ::-1]

print(arr_2d_reversed_cols)

[[5.79723513 5.43524832 5.24264863]
 [8.41069979 6.39999847 6.61474114]
 [6.24080962 8.82727778 7.57105258]
 [7.66077474 7.30623778 7.86897308]
 [8.23493398 8.00491608 7.48313339]]


Find all values between 6 and 8 in arr_2d

In [10]:
# Create a boolean mask for values between 6 and 8
mask = (arr_2d >= 6) & (arr_2d <= 8)

# Use boolean indexing to get the values between 6 and 8
values_between_6_and_8 = arr_2d[mask]

print(values_between_6_and_8)

[6.61474114 6.39999847 7.57105258 6.24080962 7.86897308 7.30623778
 7.66077474 7.48313339]


## Task 2: Pandas

Select all elements in the series bigger than the mean of the series itself

In [11]:
#Input
ser1 = pd.Series([1, 2, 3, 4, 5])

#Solution
# Calculate the mean of the series
mean_value = ser1.mean()

# Select elements greater than the mean
result = ser1[ser1 > mean_value]

print(result)

3    4
4    5
dtype: int64


Find all elements appearing both in ser1 and ser2 using isin() and create a new series with those elements

In [12]:
# Input
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])

#Solution
mask = ser1.isin(ser2)
result = ser1[mask]

print(result)

3    4
4    5
dtype: int64


In the following pandas series, keep only the 2 most frequent ones and replace everything else with 'Other'. Hint: Series have a method to count how often values appear in it.

In [13]:
# Input
np.random.RandomState(100)
ser = pd.Series(np.random.randint(1, 5, [12]))

#Solution

Import the data from Kantone_Statistiken.xlsx in a dataframe. Make sure you have the correct index and column labels

In [14]:
df = pd.read_excel('Kantone_Statistiken.xlsx', skiprows=1, index_col=0)
df

Einwohner in 1000  Ausländer in %  Fläche in km2  Arbeitslosenquote  \
Schweiz           8419.550       24.955562       41290.39               3.19   
ZH                1487.969       26.568967        1728.85               3.54   
BE                1026.513       16.063995        5959.40               2.59   
LU                 403.397       18.377182        1493.28               1.90   
UR                  36.145       11.882695        1076.30               1.01   
SZ                 155.863       20.701514         908.03               1.79   
OW                  37.378       14.677083         490.64               0.89   
NW                  42.556       14.181314         275.94               1.12   
GL                  40.147       23.655566         685.43               2.12   
ZG                 123.948       27.543002         238.71               2.42   
FR                 311.914       22.386619        1671.37               2.77   
SO                 269.441       21.971786         790.37               2.82   
BS                 193.070       35.761123          36.98               3.76   
BL                 285.624       22.278940         517.74               2.91   
SH                  80.769       25.851502         298.43               3.22   
AR                  54.954       16.213560         242.92               1.77   
AI                  16.003       11.079173         172.39               0.94   
SG                 502.552       23.823007        2030.73               2.37   
GR                 197.550       18.536067        7105.00               1.52   
AG                 663.462       24.681142        1403.95               3.15   
TG                 270.709       24.502695         991.51               2.25   
TI                 354.375       28.090864        2812.25               3.38   
VD                 784.822       33.620999        3212.21               4.52   
VS                 339.176       23.212727        5224.77               3.58   
NE                 178.567       25.586475         802.26               5.60   
GE                 489.524       40.219274         282.32               5.28   
JU                  73.122       14.566068         838.61               4.61   

         Bruttoinlandprodukt pro Einwohner in Fr.  \
Schweiz                               85120.54749   
ZH                                    96612.78594   
BE                                    76897.22500   
LU                                    66219.98282   
UR                                    53347.08857   
SZ                                    59866.91862   
OW                                    66018.56327   
NW                                    70258.57101   
GL                                    68115.78405   
ZG                                   152708.23080   
FR                                    59406.74362   
SO                                    66024.42757   
BS                                   168891.34930   
BL                                    68730.24447   
SH                                    86477.91325   
AR                                    56527.21813   
AI                                    61569.80218   
SG                                    72479.03802   
GR                                    71240.11302   
AG                                    61688.66956   
TG                                    60408.83333   
TI                                    82478.75760   
VD                                    68256.57127   
VS                                    53383.42653   
NE                                    87581.60868   
GE                                    98436.03372   
JU                                    63476.62274   

         Ohne nachobligatorische Ausbildung (ab 25 Jahren)  \
Schweiz                                               20.9   
ZH                                                    16.1   
BE                                                    18.2   
LU                                 

Find the canton with the highest 'Arbeitslosenquote' and print the name of that canton

In [15]:
# Find the canton with the highest 'Arbeitslosenquote'
max_unemployment_canton = df['Arbeitslosenquote'].idxmax()

# Print the name of the canton
print("Canton with the highest unemployment rate:", max_unemployment_canton)

Canton with the highest unemployment rate: NE


Which column correlates the most with the column 'Arbeitslosenquote'? Use the pearson correlation. 

Also, if unclear: Find out what the pearson correlation actually is.

In [16]:
# The Pearson correlation coefficient is a measure of the linear relationship between two variables. It ranges from -1 to 1, where:

# 1 indicates a perfect positive linear relationship,
# -1 indicates a perfect negative linear relationship, and
# 0 indicates no linear relationship.

# Exclude 'Arbeitslosenquote' column from the correlations
correlations = df.drop('Arbeitslosenquote', axis=1).corrwith(df['Arbeitslosenquote'])

# Find the column with the maximum correlation
max_correlation_column = correlations.idxmax()

# Get the actual correlation value
max_correlation_value = correlations.loc[max_correlation_column]

# Print the result
print("Column with the highest Pearson correlation (excluding 'Arbeitslosenquote'):", max_correlation_column)
print("Correlation value:", max_correlation_value)

Column with the highest Pearson correlation (excluding 'Arbeitslosenquote'): Ausländer in %
Correlation value: 0.7053623251825505


Find all rows where the 'Ausländer in %' is higher than the 'Hochschulabschlussquote' and which has at least 500'000 residents

In [17]:
# Filter rows based on conditions
filtered_rows = df[(df['Ausländer in %'] > df['Hochschulabschlussquote']) & (df['Einwohner in 1000'] >= 500)]

# Print the resulting DataFrame
filtered_rows

Einwohner in 1000  Ausländer in %  Fläche in km2  Arbeitslosenquote  \
ZH           1487.969       26.568967        1728.85               3.54   
SG            502.552       23.823007        2030.73               2.37   
AG            663.462       24.681142        1403.95               3.15   
VD            784.822       33.620999        3212.21               4.52   

    Bruttoinlandprodukt pro Einwohner in Fr.  \
ZH                               96612.78594   
SG                               72479.03802   
AG                               61688.66956   
VD                               68256.57127   

    Ohne nachobligatorische Ausbildung (ab 25 Jahren)  \
ZH                                               16.1   
SG                                               22.1   
AG                                               18.3   
VD                                               25.2   

    Sekundarstufe II (ab 25 Jahren)  Tertiärstufe (ab 25 Jahren)  \
ZH                             42.8                         41.1   
SG                             49.9                         28.0   
AG                             50.6                         31.1   
VD                             36.8                         38.0   

    Hochschulabschlussquote  
ZH                    22.55  
SG                    22.01  
AG                    22.61  
VD                    25.94

Add a new column 'Westschweiz' with a value of 1 if the canton belongs to western Switzerland and a 0 otherwise

In [18]:
# List of cantons in western Switzerland
western_cantons = ['VD', 'NE', 'GE', 'JU', 'FR', 'VS']

# Add a new column 'Westschweiz'
df['Westschweiz'] = df.index.isin(western_cantons).astype(int)
df

Einwohner in 1000  Ausländer in %  Fläche in km2  Arbeitslosenquote  \
Schweiz           8419.550       24.955562       41290.39               3.19   
ZH                1487.969       26.568967        1728.85               3.54   
BE                1026.513       16.063995        5959.40               2.59   
LU                 403.397       18.377182        1493.28               1.90   
UR                  36.145       11.882695        1076.30               1.01   
SZ                 155.863       20.701514         908.03               1.79   
OW                  37.378       14.677083         490.64               0.89   
NW                  42.556       14.181314         275.94               1.12   
GL                  40.147       23.655566         685.43               2.12   
ZG                 123.948       27.543002         238.71               2.42   
FR                 311.914       22.386619        1671.37               2.77   
SO                 269.441       21.971786         790.37               2.82   
BS                 193.070       35.761123          36.98               3.76   
BL                 285.624       22.278940         517.74               2.91   
SH                  80.769       25.851502         298.43               3.22   
AR                  54.954       16.213560         242.92               1.77   
AI                  16.003       11.079173         172.39               0.94   
SG                 502.552       23.823007        2030.73               2.37   
GR                 197.550       18.536067        7105.00               1.52   
AG                 663.462       24.681142        1403.95               3.15   
TG                 270.709       24.502695         991.51               2.25   
TI                 354.375       28.090864        2812.25               3.38   
VD                 784.822       33.620999        3212.21               4.52   
VS                 339.176       23.212727        5224.77               3.58   
NE                 178.567       25.586475         802.26               5.60   
GE                 489.524       40.219274         282.32               5.28   
JU                  73.122       14.566068         838.61               4.61   

         Bruttoinlandprodukt pro Einwohner in Fr.  \
Schweiz                               85120.54749   
ZH                                    96612.78594   
BE                                    76897.22500   
LU                                    66219.98282   
UR                                    53347.08857   
SZ                                    59866.91862   
OW                                    66018.56327   
NW                                    70258.57101   
GL                                    68115.78405   
ZG                                   152708.23080   
FR                                    59406.74362   
SO                                    66024.42757   
BS                                   168891.34930   
BL                                    68730.24447   
SH                                    86477.91325   
AR                                    56527.21813   
AI                                    61569.80218   
SG                                    72479.03802   
GR                                    71240.11302   
AG                                    61688.66956   
TG                                    60408.83333   
TI                                    82478.75760   
VD                                    68256.57127   
VS                                    53383.42653   
NE                                    87581.60868   
GE                                    98436.03372   
JU                                    63476.62274   

         Ohne nachobligatorische Ausbildung (ab 25 Jahren)  \
Schweiz                                               20.9   
ZH                                                    16.1   
BE                                                    18.2   
LU                                 

## Task 3: Manual Labeling
Go to https://github.com/tzutalin/labelImg and download the tool or build it locally. (Alternative, try an online labeling tool, such as https://saiwa.ai/app/annotation-service/bounding-box-annotation ) Label some of your own images and have a look at the resulting files. How long does it take you on average to label one image? Given your work would cost the company 100\\$ / hour, an image labeled by MTurk would cost you 0.02\\$ and the crowdsourcing solution would take 4 hours for you to set up: At what point would it make sense to use the crowdsourcing platform?

Optional 1: https://towardsdatascience.com/tutorial-build-an-object-detection-system-using-yolo-9a930513643a describes the process of manual labeling using Amazons Mechanical Turk and how the resulting images are applied in a machine learning system.

Optional 2: Take a look at various platforms offering manual labeling and similar tasks. An interesting list can be found here: https://www.g2.com/products/amazon-mechanical-turk/competitors/alternatives 